### PR TITLE
Add S&D

### PR DESCRIPTION
**Pull request by Tobias-B-Besemer**
Add Safer-Networking's Spybot - Search & Destroy (S&D)

### CODE REVIEW

**Comment by ScriptTiger** [comment]
@Tobias-B-Besemer, I really wanted to add this, but I don't think I can :(
http://www.nu2.nu/pebuilder/#download
https://www.safer-networking.org/en/faq/43.html

**Comment by Tobias-B-Besemer** [comment]
Sorry, that this: https://www.safer-networking.org/features/bootcd/

**Comment by ScriptTiger** [comment]
Can you update your PR to just have that link and get rid of the current one?

And just to be clear, that video shows you can make the CD completely from the installed Spybot program, right? To be honest, I am actually surprised to hear BartPE is dead, a lot of great projects used it :(

**Comment by Tobias-B-Besemer** [comment]
This way?

Guess, didn't watched! ^^ But AFAIK it was so in the past... But long time ago...

**Comment by ScriptTiger** [comment]
Yeah, thanks for making me feel old :P But that video does look pretty awesome. As soon as I have time, I'll edit your PR up and merge it.

**Comment by Tobias-B-Besemer** [comment]
Wasn't my intension to make you feel old! I just don't watched the vid, 'cause it seems to be the how-to... And I know BartPE, but after all the programs that fluted around to create this CD, or that USB-Stick, I really can't remember anymore what BartPE exactly was...
Maybe I will watch the vid later, too... And I already have BartPE in a Google Tab open to have a look on it again... But now I need a break... ^^
Yeah, edit it! Musst be terrible English... :D As I said: Not my mother language! ^^
Thx for upcoming merge! :-)

**Comment by Tobias-B-Besemer** [comment]
OK, I had a look on BartPE, again... And there is a simple reason why I did know the name, but doesn't know anymore for what it was... Because: I had the (original) Hiren's (Warez) Boot CD! ^^
To understand what the Hiren's Boot CD was, before the (light) free version came out, you maybe should have a look on the (discontinued [seems so]) 'Restored Edition'. E.g. here is the documentation to it:
ftp://193.192.37.3/download/distributive/HBCD/Hirens.Boot.DVD.15.2.Restored.Edition.1.1-Proteus/proteus.html
So there was just never the need for me to work with BartPE...

Also, when I had a quick view on the 'Restored Edition', I found the link to the 'Kaspersky Rescue Disk 2018': https://support.kaspersky.com/viruses/krd2018
I don't know if you wanna add it too and if I should make a PR for it... Maybe I do... ^^

**Comment by Tobias-B-Besemer** [comment]
And if you really miss BartPE, then you maybe can use WinPE... ^^ (...and/or mention it in your docu.)
https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/winpe-intro

**Comment by Tobias-B-Besemer** [comment]
OK, I found now the time to have a look at the vid about the S&D CD...
Looks good!
And I also can see in the vid (in the status msgs, when the CD is created), that it use WinPE... ;-)

**Comment by ScriptTiger** [comment]
Thanks! It will take some time to review all this, as I am currently busy with some work, but be patient :)

WinPE looks like a nice replacement, but to be honest the major problem with both BartPE and WinPE is they include Microsoft and they cannot be distributed as ISOs and everyone has to "build" the disk themself from their own operating system for licensing purposes, which is why you can't download the boot disk and you have to make it with the software. I think using ReactOS would be better, and you could legally host the ISOs for download since it's open source. I think including all of those tools in a ReactOS live disk would be awesome.

**Comment by Tobias-B-Besemer** [comment]
Yeah, no prob! Take your time! :-)

I know about the license issues with BartPE & WinPE... The 'idea' was to point the user to WinPE under e.g. 'Other Useful Tools' to inform him, that he can build his own Rescue CD/DVD/USB-Stick if he like to...
There are also a lot of (German) articles from IT-Magazines around how this can be made...
But it seems to be hard to find a good english one... :-/
But here I found some how-tos that don't look so bad for the beginning:
https://4sysops.com/archives/build-a-bootable-windows-pe-3-0-usb-drive-with-rescue-tools-part-1/
https://4sysops.com/archives/create-a-bootable-windows-pe-3-0-usb-drive-with-rescue-tools-part-2/
So maybe you get interested in maybe make a new/better how-to in your project in a second file...
...it may also depend on which tools you find in other, abandoned projects, that a user 'should have' for maintain a system...
(Btw.: I found some notes by Hiren's Homepage about free tools to restore deleted files/systems...)

AFAIK unfortunately ReactOS isn't yet in the state, that it supports all 'necessary' Core-Features, so you maybe run into some problems with e.g. hard-, or software-support...
I'm also waiting ravenous on a more usable Beta Version that can be used e.g. for a Rescue System and I think this will push projects like e.g. UBCD (and derivatives) much forward...

**Pull request closed without merging**
