### PR TITLE
Tools to remove other harmfull software

### PR DESCRIPTION
**Pull request by Tobias-B-Besemer**
As I'm (still) not so deep into GitHub, I hope I don't mess up to much and don't make to much work with my PRs!

This PR would make Pull Request #5 obsolete!

### CODE REVIEW

**Comment by Tobias-B-Besemer** [comment]
Just as an idea:
Maybe a next step can be to split 'Removal Tools' into a new file and maybe move all how-to-data of the README.md also into a new (TXT) file so that it's also readable after an download on a Win-System (and to have the same 'look & feel' in all how-to-files of the project)...

**Comment by Tobias-B-Besemer** [comment]
...because:
If we go straight ahead, I would now make PRs for Malwarebyte's AdwCleaner (thought it's MBAR) and SUPERAntiSpyware... and then move the 'Anti-Ad- & Spyware'-Tools together again and add maybe other Anti-Rootkit-Tools (or things not covered by AV-Solutions) to it again... and this would make your 911-List a list that have mainly 'Removal Tools' in it... and that would look at least 'confusing'... ^^

**Comment by ScriptTiger** [comment]
Lol, just finish up with what you want to add then so I can see what it all looks like together and review it at the same time :P I can always edit and remove things myself, so I would prefer you give me too much so I have more options.

**Comment by Tobias-B-Besemer** [comment]
And I prefer to make small steps, give you the control, and you always can say 'Stop!' and 'No!'... ^^
...and so I don't wast to much time with PRs, that get later not excepted... ^^

**Comment by ScriptTiger** [comment]
I am not sure if you intended that to sound like a BDSM relationship, but...

And maybe you've noticed from my other issues that I don't have any problems writing a lot, even rewriting entire PRs and still merging :P Steven Black hates my lackluster GitHub etiquette, but I just like doing things my own way.

**Pull request closed without merging**
